### PR TITLE
Add confirmation dialog before creating contract

### LINKED ISSUE #70: Add a message that a customer will not be able to change a value of a contract
In the interface for creating a contract we would like to have a message that the customer will not be able to change the cost of the contract after it has been created and double-check that customer has agreed on the cost with a contractor before creating the contract.

I suggest to use existing component: https://github.com/optriment/optrispace-frontend-v2/blob/master/src/components/ConfirmationMessage/index.jsx

How this component is used: https://github.com/optriment/optrispace-frontend-v2/blob/master/src/components/ContractCardForCustomer/index.jsx#L238

How this task can be implemented:
1. Customer opens an interface to create a new contract for a contractor
2. If all UI validations passed, "Add New" button will be enabled (it is already implemented)
3. Click on this button opens a confirmation dialog with hardcoded description
4. Customer should pick between two buttons: to decline this dialog or confirm a creation of the contract

### PR DESCRIPTION
**Pull request by Aditya-A-G**
Fixes #70 

get_feedback

### CODE REVIEW

**Comment by Aditya-A-G** [comment]
@gruz0 please let me know if any changes are needed

**Comment by gruz0** [comment]
@Aditya-A-G, amazing! It works like a charm!

**Comment by Aditya-A-G** [comment]
@gruz0 Thank you for merging my pull request! Please let me know if there are any other tasks or issues I can help with.

**Comment by gruz0** [comment]
@Aditya-A-G, sure! I am working on writing a documentation for our smart contracts. After that I will add a new function to manage freelancers' profiles and it would be great to add an implementation on the frontend.

Can we discuss your part-time employment (and be paid in crypto) to manage our frontend tasks?

**Comment by Aditya-A-G** [comment]
Thank you for the opportunity, @gruz0. I am definitely interested in working with you on the frontend tasks and being paid in crypto. Let's discuss the details further. Would you like to continue the conversation on Discord or schedule a call?

**Pull request merged**
